<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = $this->getAllPaises();
        DB::table('pais')->insert($paises);
    }

    private function getAllPaises(){
        return [
            ["nome" => "Afghanistan", "sigla" => "AF"],
            ["nome" => "Albania", "sigla" => "AL"],
            ["nome" => "Algeria", "sigla" => "DZ"],
            ["nome" => "Andorra", "sigla" => "AD"],
            ["nome" => "Angola", "sigla" => "AO"],
            ["nome" => "Antigua and Barbuda", "sigla" => "AG"],
            ["nome" => "Argentina", "sigla" => "AR"],
            ["nome" => "Armenia", "sigla" => "AM"],
            ["nome" => "Australia", "sigla" => "AU"],
            ["nome" => "Austria", "sigla" => "AT"],
            ["nome" => "Azerbaijan", "sigla" => "AZ"],
            ["nome" => "Bahamas", "sigla" => "BS"],
            ["nome" => "Bahrain", "sigla" => "BH"],
            ["nome" => "Bangladesh", "sigla" => "BD"],
            ["nome" => "Barbados", "sigla" => "BB"],
            ["nome" => "Belarus", "sigla" => "BY"],
            ["nome" => "Belgium", "sigla" => "BE"],
            ["nome" => "Belize", "sigla" => "BZ"],
            ["nome" => "Benin", "sigla" => "BJ"],
            ["nome" => "Bhutan", "sigla" => "BT"],
            ["nome" => "Bolivia", "sigla" => "BO"],
            ["nome" => "Bosnia and Herzegovina", "sigla" => "BA"],
            ["nome" => "Botswana", "sigla" => "BW"],
            ["nome" => "Brazil", "sigla" => "BR"],
            ["nome" => "Brunei", "sigla" => "BN"],
            ["nome" => "Bulgaria", "sigla" => "BG"],
            ["nome" => "Burkina Faso", "sigla" => "BF"],
            ["nome" => "Burundi", "sigla" => "BI"],
            ["nome" => "Cabo Verde", "sigla" => "CV"],
            ["nome" => "Cambodia", "sigla" => "KH"],
            ["nome" => "Cameroon", "sigla" => "CM"],
            ["nome" => "Canada", "sigla" => "CA"],
            ["nome" => "Central African Republic", "sigla" => "CF"],
            ["nome" => "Chad", "sigla" => "TD"],
            ["nome" => "Chile", "sigla" => "CL"],
            ["nome" => "China", "sigla" => "CN"],
            ["nome" => "Colombia", "sigla" => "CO"],
            ["nome" => "Comoros", "sigla" => "KM"],
            ["nome" => "Congo", "sigla" => "CG"],
            ["nome" => "Congo (DRC)", "sigla" => "CD"],
            ["nome" => "Costa Rica", "sigla" => "CR"],
            ["nome" => "Croatia", "sigla" => "HR"],
            ["nome" => "Cuba", "sigla" => "CU"],
            ["nome" => "Cyprus", "sigla" => "CY"],
            ["nome" => "Czech Republic", "sigla" => "CZ"],
            ["nome" => "Denmark", "sigla" => "DK"],
            ["nome" => "Djibouti", "sigla" => "DJ"],
            ["nome" => "Dominica", "sigla" => "DM"],
            ["nome" => "Dominican Republic", "sigla" => "DO"],
            ["nome" => "East Timor", "sigla" => "TL"],
            ["nome" => "Ecuador", "sigla" => "EC"],
            ["nome" => "Egypt", "sigla" => "EG"],
            ["nome" => "El Salvador", "sigla" => "SV"],
            ["nome" => "Equatorial Guinea", "sigla" => "GQ"],
            ["nome" => "Eritrea", "sigla" => "ER"],
            ["nome" => "Estonia", "sigla" => "EE"],
            ["nome" => "Eswatini", "sigla" => "SZ"],
            ["nome" => "Ethiopia", "sigla" => "ET"],
            ["nome" => "Fiji", "sigla" => "FJ"],
            ["nome" => "Finland", "sigla" => "FI"],
            ["nome" => "France", "sigla" => "FR"],
            ["nome" => "Gabon", "sigla" => "GA"],
            ["nome" => "Gambia", "sigla" => "GM"],
            ["nome" => "Georgia", "sigla" => "GE"],
            ["nome" => "Germany", "sigla" => "DE"],
            ["nome" => "Ghana", "sigla" => "GH"],
            ["nome" => "Greece", "sigla" => "GR"],
            ["nome" => "Grenada", "sigla" => "GD"],
            ["nome" => "Guatemala", "sigla" => "GT"],
            ["nome" => "Guinea", "sigla" => "GN"],
            ["nome" => "Guinea-Bissau", "sigla" => "GW"],
            ["nome" => "Guyana", "sigla" => "GY"],
            ["nome" => "Haiti", "sigla" => "HT"],
            ["nome" => "Honduras", "sigla" => "HN"],
            ["nome" => "Hungary", "sigla" => "HU"],
            ["nome" => "Iceland", "sigla" => "IS"],
            ["nome" => "India", "sigla" => "IN"],
            ["nome" => "Indonesia", "sigla" => "ID"],
            ["nome" => "Iran", "sigla" => "IR"],
            ["nome" => "Iraq", "sigla" => "IQ"],
            ["nome" => "Ireland", "sigla" => "IE"],
            ["nome" => "Israel", "sigla" => "IL"],
            ["nome" => "Italy", "sigla" => "IT"],
            ["nome" => "Jamaica", "sigla" => "JM"],
            ["nome" => "Japan", "sigla" => "JP"],
            ["nome" => "Jordan", "sigla" => "JO"],
            ["nome" => "Kazakhstan", "sigla" => "KZ"],
            ["nome" => "Kenya", "sigla" => "KE"],
            ["nome" => "Kiribati", "sigla" => "KI"],
            ["nome" => "Kuwait", "sigla" => "KW"],
            ["nome" => "Kyrgyzstan", "sigla" => "KG"],
            ["nome" => "Laos", "sigla" => "LA"],
            ["nome" => "Latvia", "sigla" => "LV"],
            ["nome" => "Lebanon", "sigla" => "LB"],
            ["nome" => "Lesotho", "sigla" => "LS"],
            ["nome" => "Liberia", "sigla" => "LR"],
            ["nome" => "Libya", "sigla" => "LY"],
            ["nome" => "Liechtenstein", "sigla" => "LI"],
            ["nome" => "Lithuania", "sigla" => "LT"],
            ["nome" => "Luxembourg", "sigla" => "LU"],
            ["nome" => "Madagascar", "sigla" => "MG"],
            ["nome" => "Malawi", "sigla" => "MW"],
            ["nome" => "Malaysia", "sigla" => "MY"],
            ["nome" => "Maldives", "sigla" => "MV"],
            ["nome" => "Mali", "sigla" => "ML"],
            ["nome" => "Malta", "sigla" => "MT"],
            ["nome" => "Marshall Islands", "sigla" => "MH"],
            ["nome" => "Mauritania", "sigla" => "MR"],
            ["nome" => "Mauritius", "sigla" => "MU"],
            ["nome" => "Mexico", "sigla" => "MX"],
            ["nome" => "Micronesia", "sigla" => "FM"],
            ["nome" => "Moldova", "sigla" => "MD"],
            ["nome" => "Monaco", "sigla" => "MC"],
            ["nome" => "Mongolia", "sigla" => "MN"],
            ["nome" => "Montenegro", "sigla" => "ME"],
            ["nome" => "Morocco", "sigla" => "MA"],
            ["nome" => "Mozambique", "sigla" => "MZ"],
            ["nome" => "Myanmar", "sigla" => "MM"],
            ["nome" => "Namibia", "sigla" => "NA"],
            ["nome" => "Nauru", "sigla" => "NR"],
            ["nome" => "Nepal", "sigla" => "NP"],
            ["nome" => "Netherlands", "sigla" => "NL"],
            ["nome" => "New Zealand", "sigla" => "NZ"],
            ["nome" => "Nicaragua", "sigla" => "NI"],
            ["nome" => "Niger", "sigla" => "NE"],
            ["nome" => "Nigeria", "sigla" => "NG"],
            ["nome" => "North Korea", "sigla" => "KP"],
            ["nome" => "North Macedonia", "sigla" => "MK"],
            ["nome" => "Norway", "sigla" => "NO"],
            ["nome" => "Oman", "sigla" => "OM"],
            ["nome" => "Pakistan", "sigla" => "PK"],
            ["nome" => "Palau", "sigla" => "PW"],
            ["nome" => "Panama", "sigla" => "PA"],
            ["nome" => "Papua New Guinea", "sigla" => "PG"],
            ["nome" => "Paraguay", "sigla" => "PY"],
            ["nome" => "Peru", "sigla" => "PE"],
            ["nome" => "Philippines", "sigla" => "PH"],
            ["nome" => "Poland", "sigla" => "PL"],
            ["nome" => "Portugal", "sigla" => "PT"],
            ["nome" => "Qatar", "sigla" => "QA"],
            ["nome" => "Romania", "sigla" => "RO"],
            ["nome" => "Russia", "sigla" => "RU"],
            ["nome" => "Rwanda", "sigla" => "RW"],
            ["nome" => "Saint Kitts and Nevis", "sigla" => "KN"],
            ["nome" => "Saint Lucia", "sigla" => "LC"],
            ["nome" => "Saint Vincent and the Grenadines", "sigla" => "VC"],
            ["nome" => "Samoa", "sigla" => "WS"],
            ["nome" => "San Marino", "sigla" => "SM"],
            ["nome" => "Sao Tome and Principe", "sigla" => "ST"],
            ["nome" => "Saudi Arabia", "sigla" => "SA"],
            ["nome" => "Senegal", "sigla" => "SN"],
            ["nome" => "Serbia", "sigla" => "RS"],
            ["nome" => "Seychelles", "sigla" => "SC"],
            ["nome" => "Sierra Leone", "sigla" => "SL"],
            ["nome" => "Singapore", "sigla" => "SG"],
            ["nome" => "Slovakia", "sigla" => "SK"],
            ["nome" => "Slovenia", "sigla" => "SI"],
            ["nome" => "Solomon Islands", "sigla" => "SB"],
            ["nome" => "Somalia", "sigla" => "SO"],
            ["nome" => "South Africa", "sigla" => "ZA"],
            ["nome" => "South Korea", "sigla" => "KR"],
            ["nome" => "South Sudan", "sigla" => "SS"],
            ["nome" => "Spain", "sigla" => "ES"],
            ["nome" => "Sri Lanka", "sigla" => "LK"],
            ["nome" => "Sudan", "sigla" => "SD"],
            ["nome" => "Suriname", "sigla" => "SR"],
            ["nome" => "Sweden", "sigla" => "SE"],
            ["nome" => "Switzerland", "sigla" => "CH"],
            ["nome" => "Syria", "sigla" => "SY"],
            ["nome" => "Taiwan", "sigla" => "TW"],
            ["nome" => "Tajikistan", "sigla" => "TJ"],
            ["nome" => "Tanzania", "sigla" => "TZ"],
            ["nome" => "Thailand", "sigla" => "TH"],
            ["nome" => "Togo", "sigla" => "TG"],
            ["nome" => "Tonga", "sigla" => "TO"],
            ["nome" => "Trinidad and Tobago", "sigla" => "TT"],
            ["nome" => "Tunisia", "sigla" => "TN"],
            ["nome" => "Turkey", "sigla" => "TR"],
            ["nome" => "Turkmenistan", "sigla" => "TM"],
            ["nome" => "Tuvalu", "sigla" => "TV"],
            ["nome" => "Uganda", "sigla" => "UG"],
            ["nome" => "Ukraine", "sigla" => "UA"],
            ["nome" => "United Arab Emirates", "sigla" => "AE"],
            ["nome" => "United Kingdom", "sigla" => "GB"],
            ["nome" => "United States", "sigla" => "US"],
            ["nome" => "Uruguay", "sigla" => "UY"],
            ["nome" => "Uzbekistan", "sigla" => "UZ"],
            ["nome" => "Vanuatu", "sigla" => "VU"],
            ["nome" => "Vatican City", "sigla" => "VA"],
            ["nome" => "Venezuela", "sigla" => "VE"],
            ["nome" => "Vietnam", "sigla" => "VN"],
            ["nome" => "Yemen", "sigla" => "YE"],
            ["nome" => "Zambia", "sigla" => "ZM"],
            ["nome" => "Zimbabwe", "sigla" => "ZW"],
        ];

    }
}
